name: Python CI

on:
  push:
    branches: [ main ]
    paths:
      - 'app/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'app/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt

    - name: Check code formatting with isort and black
      run: |
        isort --check app
        black --check app

    - name: Run static code analysis with flake8
      run: |
        flake8 app

    - name: Run Pytest
      run: pytest
